spring.application.name=placementmanagementsystem

server.port=8081
springdoc.swagger-ui.path=/docs

spring.datasource.url=jdbc:postgresql://localhost:5433/placementmanagementsystem
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update