spring.application.name=placementmanagementsystem

server.port=8081
springdoc.swagger-ui.path=/docs

spring.datasource.url=jdbc:postgresql://localhost:5433/placementmanagementsystem
spring.datasource.username=postgres
spring.datasource.password=Tanmay@1234

spring.jpa.hibernate.ddl-auto=update